### ISSUE TITLE
Bug alignment with "experimental font compensation"

### ISSUE THREAD

**Issue by VanSlanzar** [Flat-Badger-1971/BarSteward#15]
You can see below that fps, latency, and mount time are no longer aligned with the "font compensation" option enabled.
![Screenshot_20](https://user-images.githubusercontent.com/61565834/208249316-2f1a7ff5-e260-4eb9-a58c-4645f4c87f32.png)

![Screenshot_41](https://user-images.githubusercontent.com/61565834/208249396-ca0f3681-c987-4032-a272-eb7c407b9b1d.png)

**Comment by Flat-Badger-1971** [comment]
I'm not able to reproduce that, but I do know why it's happening. I've done a change for 1.4.24 which I've just pushed to git - would you be able to check it on your pc please?

**Comment by VanSlanzar** [comment]
the corrections made seem to work well. Yes I have a lot of widgets ^^. I like to see the news directly. the teso menu is not really optimized.
