### ISSUE TITLE
D5398462 UI Error

### ISSUE THREAD

**Issue by denniskuligin** [Flat-Badger-1971/BarSteward#33]
Hey there.
Your yesterday's commit caused the following message and totally unable to use ur bar:

user:/AddOns/BarSteward/ui/widget.lua:339: operator + is not supported for nil + number
stack traceback:
user:/AddOns/BarSteward/ui/widget.lua:339: in function 'baseWidget:SetPadding'
user:/AddOns/BarSteward/ui/widget.lua:641: in function 'BS.CreateWidget'
user:/AddOns/BarSteward/ui/bar.lua:621: in function 'baseBar:AddWidgets'
user:/AddOns/BarSteward/misc/utility.lua:1413: in function 'BS.GenerateBar'
user:/AddOns/BarSteward/BarSteward.lua:97: in function 'BS.ContinueIntialising'
user:/AddOns/BarSteward/BarSteward.lua:176: in function 'Initialise'
user:/AddOns/BarSteward/BarSteward.lua:186: in function 'BS.OnAddonLoaded'

**Comment by denniskuligin** [comment]
![image](https://github.com/user-attachments/assets/b0402f68-c12b-4109-94ab-91d3e300ca09)

**Comment by denniskuligin** [comment]
![image](https://github.com/user-attachments/assets/8d035461-b27c-49f8-aa09-8098f3b52bba)

I locally fixed it with the following changes to SetPadding method:

`    if (horizontalPadding) then
        self.horizontalPadding = horizontalPadding + 10
    else
        self.horizontalPadding = 10
    end

    self.minVertical = self.iconSize

    if(verticalPadding) then
        self.verticalPadding = verticalPadding + self.minVertical
    else
        self.verticalPadding = self.minVertical
    end`

**Comment by Flat-Badger-1971** [comment]
Apologies - I did see your report then completely forgot you'd made it. It's fixed now, thanks for taking the time to report it.
